spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/patient_service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
springdoc:
   swagger-ui:
     path: /swagger-ui.html
   api-docs:
     path: /api-docs
